### ISSUE TITLE
sxm client issue

### ISSUE THREAD

**Issue by antykon** [AngellusMortis/sxm-client#1]
* sxm-client version:  0.1.0
* Python version: 3.8
* Operating System: Windows 10

### Description

I tried to connect on VLC but it only happened once. In every other attempt i had the messages below. Please note that I'm outside the US and, thus, tried to connect through a VPN since SiriusXM doesn't work otherwise on browsers or apps. Thank you.

### What I Did

Command:
sxm --username (my username) --password (my password)

Output:
INFO:c:\python38\lib\site-packages\sxm\http.py:running SXM proxy server on http://127.0.0.1:9999
WARNING:c:\python38\lib\site-packages\sxm\client.py:Received status code 403 for path 'modify/authentication'
ERROR:c:\python38\lib\site-packages\sxm\client.py:Unable to authenticate because login failed

(the last 2 lines are constantly repeated)

**Comment by antykon** [comment]
Also, when entering just sxm as a command it doesn't let me enter a password (as in it doesn't let me write anything next to "Password:".

**Comment by rollnthndr** [comment]
I'm having the same authentication error as well. Wondering if maybe the Sirius 'api' has changed or something?

**Comment by rollnthndr** [comment]
Also, I'd like to be able to run the VSCode debugger and work my way through it to see where and what is failing but I can't get this app to run the source code. The only way I can seem to run it is by 'installing' it. Any hints as to how to run the source code would be appreciated. Thanks to anyone...

**Comment by alejandro-ayestaran** [comment]
Same issue happening on Mac (OS Catalina):
 ~ % sxm -l      
Username: *deleted*
Password: 
WARNING:/usr/local/lib/python3.7/site-packages/sxm/client.py:Received status code 403 for path 'modify/authentication'
ERROR:/usr/local/lib/python3.7/site-packages/sxm/client.py:Unable to authenticate because login failed

It doesn't matter if I try the client or setting username and password using env variables.
Auth simply doesn't work. :-(

AA

**Comment by alejandro-ayestaran** [comment]
Having the same issue (Mac OS Catalina)

 ~ % sxm -l      
Username: *deleted*
Password: 
WARNING:/usr/local/lib/python3.7/site-packages/sxm/client.py:Received status code 403 for path 'modify/authentication'
ERROR:/usr/local/lib/python3.7/site-packages/sxm/client.py:Unable to authenticate because login failed

It doesn't matter if I pass the username/password interactively or via environment variables. It happens with the client as well as regular sxm application.

:-(

**Comment by aghassemlouei** [comment]
Same here but with macos 10.15.4 and python 3.7

**Comment by simondsmason** [comment]
Same issue here.

**Comment by krkeegan** [comment]
I think this tool may be dead.  I poked around the login issue and it seems to me that Sirius is using a user validation tool from this company:

https://nudatasecurity.com/solutions/nudetect-for-continuous-validation/

It appears to use a whole bunch of javascript to determine if you are a real human.  It appears primarily designed to prevent financial fraud so it is not too shabby.

Unless anyone has a great idea, I don't see a solution.
